cluster_name = "local-cluster"
location = "local-2"
server_id = 2
local_deployment = true
summary_filepath = "../benchmarks/logs/local-run/client-2.json"
output_filepath = "../benchmarks/logs/local-run/client-2.csv"

[[requests]]
duration_sec = 5
requests_per_sec = 10
read_ratio = 0.25

[[requests]]
duration_sec = 10
requests_per_sec = 1
read_ratio = 0.25

